### ISSUE TITLE
Kurang hari dari jadwal

### ISSUE THREAD

**Issue by habib-roy** [habib-roy/info-vaksin-sleman#1]
Perlu set timezone atribut `Date.now()` dengan local time browser, agar lebih akurat sesuai waktu pengguna.

![image](https://user-images.githubusercontent.com/8232442/125769708-b6216d81-03ed-49e7-aa39-082e80c34893.png)

**Comment by khayatzen** [comment]
Data tanggal di API pake timezone mana? 

Kalau misal pake package momentjs akan membebani banget ndak?

**Comment by habib-roy** [comment]
> Data tanggal di API pake timezone mana?
> 
> Kalau misal pake package momentjs akan membebani banget ndak?

Data dari sumber API ngga ada timezone @khayatzen , output yang kita bikin juga belum ada, seharusnya timezone masuk `Asia/Jakarta` atau `+07`
Kalo pakai momentjs sepertinya akan makan source vercel @khayatzen , bagaimana kalo pakai [day.js](https://day.js.org) ?

**Comment by khayatzen** [comment]
> Kalo pakai momentjs sepertinya akan makan source vercel @khayatzen , bagaimana kalo pakai [day.js](https://day.js.org) ?

Baik, kalau kebutuhannya sesimple itu sebenernya kita gak butuh third party packages. @habib-roy Aku vote untuk bikin method sederhana aja

**Comment by habib-roy** [comment]
> > Kalo pakai momentjs sepertinya akan makan source vercel @khayatzen , bagaimana kalo pakai [day.js](https://day.js.org) ?
> 
> Baik, kalau kebutuhannya sesimple itu sebenernya kita gak butuh third party packages. @habib-roy Aku vote untuk bikin method sederhana aja

Sepakat yat @khayatzen :100:

**Comment by khayatzen** [comment]
Okay @habib-roy , aku ambil task ini

**Comment by habib-roy** [comment]
> Okay @habib-roy , aku ambil task ini

Mantap :+1:

**Comment by khayatzen** [comment]
@habib-roy aku udah bikin Pull Request https://github.com/habib-roy/info-vaksin-sleman/pull/4

**Comment by habib-roy** [comment]
Closed #4

**Comment by habib-roy** [comment]
Barusan aku cek ternyata masih terjadi selisih @khayatzen , aku buka lagi ya issue ini.

![image](https://user-images.githubusercontent.com/8232442/126019047-f65c20f3-7dd5-4a6f-9482-d26e4dc23e10.png)

**Comment by khayatzen** [comment]
@habib-roy ternyata iya, perhitungan masih salah. Udah aku coba benerin lagi dan ajuin PR https://github.com/habib-roy/info-vaksin-sleman/pull/7

Aku nambahin method `hitungHari` coba diuji dulu

**Comment by habib-roy** [comment]
Sudah dicek, hasil preview nya juga bener, ntap :+1: LGTM :ocean: 
Thanks @khayatzen
